# Site settings
title: 瀚爷的小窝
email: lizihan0328@gmail.com
description: 技术渣成长日记
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.hans-lizihan.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github: hans-lizihan
# codepen:  username
# dribbble: username
google_analytics: UA-54903520-2

# Comment
disqus_shortname: hanslizihancom

# Build settings
markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge

sass:
  style: compressed
plugins:
  - jekyll-sitemap
